version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: restaurant_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: restaurant_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - restaurant_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant_api
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PORT: 3000
      API_KEY: secreto123
      POSTGRES_URL: postgres://postgres:password123@postgres:5432/restaurant_db
      N8N_WEBHOOK_URL: http://n8n:5678/webhook/orden-estatus
    networks:
      - restaurant_network

  nginx:
    image: nginx:1-alpine
    container_name: restaurant_nginx
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - restaurant_network

  n8n:
    image: docker.n8n.io/n8n/n8n
    container_name: restaurant_n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      N8N_HOST: localhost
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      NODE_ENV: production
      WEBHOOK_URL: http://localhost:5678/
      N8N_ENFORCED_SETTINGS: '{"webhookUrl":"http://n8n:5678/"}'
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - restaurant_network

volumes:
  postgres_data:
  n8n_data:

networks:
  restaurant_network:
    driver: bridge
